CREATE TABLE USER_IOT(USERNAME VARCHAR(50), PASSWORD VARCHAR(50), UID VARCHAR(50) PRIMARY KEY);
CREATE TABLE ADMINISTRATOR(ADMIN_NAME VARCHAR(50), ADMIN_PASSWORD VARCHAR(50), ADMIN_ID VARCHAR(50) PRIMARY KEY);
CREATE TABLE AGREEGATOR(AGREEGATOR_ID VARCHAR(50) PRIMARY KEY, UID VARCHAR(50), GROUP_ID VARCHAR(50));
CREATE TABLE DEVICE(DEVICE_ID VARCHAR(50) PRIMARY KEY, DEVICE_IP_ADDRESS VARCHAR(50), DEVICE_APP_ID VARCHAR(50), GROUP_ID VARCHAR(50) PRIMARY KEY, UID VARCHAR(50));
CREATE TABLE GROUP_IOT(GROUP_NAME VARCHAR(50), GROUP_ID VARCHAR(50) PRIMARY KEY, UID VARCHAR(50));
CREATE TABLE USER_GROUP(RECORD_NUM INT AUTO_INCREMENT PRIMARY KEY, GROUP_ID VARCHAR(50), UID VARCHAR(50), AGREEGATOR_ID VARCHAR(50), DEVICE_ID VARCHAR(50));
INSERT INTO ADMINISTRATOR (ADMIN_NAME, ADMIN_PASSWORD, ADMIN_ID) VALUE("Admin","Ujjwal1234$", "1234567890");